//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecIFicator.DefaultPlugin.Resources.BlazorComponents {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainToolbar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainToolbar() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpecIFicator.DefaultPlugin.Resources.BlazorComponents.MainToolbar", typeof(MainToolbar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error_DialogTitle {
            get {
                return ResourceManager.GetString("Error.DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editor type not found.  ähnelt.
        /// </summary>
        internal static string Error_EditorTypeNotFound {
            get {
                return ResourceManager.GetString("Error.EditorTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add statement ähnelt.
        /// </summary>
        internal static string Label_AddStatement {
            get {
                return ResourceManager.GetString("Label.AddStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comments ähnelt.
        /// </summary>
        internal static string Label_Comments {
            get {
                return ResourceManager.GetString("Label.Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Resource ähnelt.
        /// </summary>
        internal static string Label_DeleteResource {
            get {
                return ResourceManager.GetString("Label.DeleteResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Resource ähnelt.
        /// </summary>
        internal static string Label_EditResource {
            get {
                return ResourceManager.GetString("Label.EditResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dual view ähnelt.
        /// </summary>
        internal static string Label_EnableMultilanguage {
            get {
                return ResourceManager.GetString("Label.EnableMultilanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit Editor ähnelt.
        /// </summary>
        internal static string Label_Exit {
            get {
                return ResourceManager.GetString("Label.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multilingualism ähnelt.
        /// </summary>
        internal static string Label_MultilanguageSupport {
            get {
                return ResourceManager.GetString("Label.MultilanguageSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Resource ähnelt.
        /// </summary>
        internal static string Label_NewResource {
            get {
                return ResourceManager.GetString("Label.NewResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected Resource and all child elements are removed. Are you sure? ähnelt.
        /// </summary>
        internal static string Text_DeleteResource {
            get {
                return ResourceManager.GetString("Text.DeleteResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Comment ähnelt.
        /// </summary>
        internal static string Title_AddComment {
            get {
                return ResourceManager.GetString("Title.AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new statement... ähnelt.
        /// </summary>
        internal static string Title_AddStatement {
            get {
                return ResourceManager.GetString("Title.AddStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Resource ähnelt.
        /// </summary>
        internal static string Title_DeleteResource {
            get {
                return ResourceManager.GetString("Title.DeleteResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Resource... ähnelt.
        /// </summary>
        internal static string Title_EditResource {
            get {
                return ResourceManager.GetString("Title.EditResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Resource... ähnelt.
        /// </summary>
        internal static string Title_NewResource {
            get {
                return ResourceManager.GetString("Title.NewResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New child resource ähnelt.
        /// </summary>
        internal static string Tooltip_NewChildResource {
            get {
                return ResourceManager.GetString("Tooltip.NewChildResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New resource above ähnelt.
        /// </summary>
        internal static string Tooltip_NewResourceAbove {
            get {
                return ResourceManager.GetString("Tooltip.NewResourceAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New resource below ähnelt.
        /// </summary>
        internal static string Tooltip_NewResourceBelow {
            get {
                return ResourceManager.GetString("Tooltip.NewResourceBelow", resourceCulture);
            }
        }
    }
}
